#!/usr/bin/env node
/**
 * Comprehensive end-to-end test for the create-subatom CLI.
 *
 * This test:
 *   1. Builds the CLI (if not already built)
 *   2. Runs a full matrix of scenarios covering:
 *        - Both languages: TypeScript, JavaScript
 *        - All ORMs: Prisma, Drizzle, Mongoose
 *        - All databases: PostgreSQL, MySQL, SQLite, MongoDB
 *        - Feature toggles: Redis, ESLint, Vitest (on / off)
 *   3. Drives the interactive prompts via an `expect` PTY script for each scenario
 *   4. Verifies the generated project structure, package.json, git repo, and
 *      feature-specific files for each scenario
 *   5. Cleans up the temporary directory
 *
 * Usage:
 *   node tests/e2e/run-e2e.mjs
 *
 * Prerequisites:
 *   - `expect` must be installed (built into macOS at /usr/bin/expect)
 *   - Node.js >= 18
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..", "..");
const CLI_ENTRY = path.join(PROJECT_ROOT, "dist", "index.js");
const EXPECT_DRIVER = path.join(__dirname, "expect-driver.exp");

// ===========================================================================
// Test Matrix
// ===========================================================================
//
// Every (language x orm x database) combination, each run with the maximum
// feature set (Redis + ESLint + Vitest) so every code-generation path is
// exercised at least once.
//
// DATABASE_MATRIX defines, per ORM, the valid database options.
const DATABASE_MATRIX = {
  prisma: ["postgresql", "mysql", "sqlite"],
  drizzle: ["postgresql", "mysql", "sqlite"],
  mongoose: ["mongodb"],
};

// Build the full matrix of scenarios.
const SCENARIOS = [];
for (const language of ["ts", "js"]) {
  for (const orm of Object.keys(DATABASE_MATRIX)) {
    for (const database of DATABASE_MATRIX[orm]) {
      SCENARIOS.push({
        language,
        orm,
        database,
        // Maximum feature set for full matrix runs.
        useRedis: true,
        useEslint: true,
        useVitest: true,
      });
    }
  }
}

// A control scenario with ALL features disabled, to verify the feature
// toggles actually turn things off (no redis/eslint/vitest artifacts).
const NO_FEATURES_SCENARIO = {
  language: "ts",
  orm: "prisma",
  database: "postgresql",
  useRedis: false,
  useEslint: false,
  useVitest: false,
};

const ALL_SCENARIOS = [...SCENARIOS, NO_FEATURES_SCENARIO];

// ===========================================================================
// Per-ORM / Per-Database expected artifacts
// ===========================================================================

/** Common files generated for every project regardless of options. */
function commonFiles(language) {
  const ext = language === "ts" ? "ts" : "js";
  return [
    ".gitignore",
    "Readme.md",
    "public/index.html",
    `src/server.${ext}`,
    `scripts/setup.env.${ext}`,
    `subatom.config.${ext}`,
  ];
}

/** Files only generated by the TypeScript template. */
function tsOnlyFiles() {
  return ["tsconfig.json"];
}

/** Files generated by the Prisma config handler. */
function prismaFiles(language) {
  const ext = language === "ts" ? "ts" : "js";
  return [
    `main.${ext}`,
    `prisma.${ext}`,
    `prisma.config.${ext}`,
    ".env.requirements",
    `src/config/__env.${ext}`,
    "src/models/subatom.prisma",
    "prisma/schema.prisma",
    `scripts/schema_builder.${ext}`,
  ];
}

/** Files generated by the Drizzle config handler (plus per-db extras). */
function drizzleFiles(language, database) {
  const ext = language === "ts" ? "ts" : "js";
  const files = [
    `main.${ext}`,
    `drizzle.config.${ext}`,
    ".env.requirements",
    `src/models/subatom.model.${ext}`,
    `src/db/schema.${ext}`,
    `src/db/db_pool.${ext}`,
    `src/config/__env.${ext}`,
  ];
  if (database === "mysql") {
    files.push(
      `src/db/dbUrl.${ext}`,
      `src/db/migrate.${ext}`,
      `src/db/reset.${ext}`,
    );
  }
  if (database === "sqlite") {
    files.push(`src/db/seed.${ext}`);
  }
  return files;
}

/** Files generated by the Mongoose config handler. */
function mongooseFiles(language) {
  const ext = language === "ts" ? "ts" : "js";
  return [
    `main.${ext}`,
    ".env.requirements",
    `src/models/subatom.model.${ext}`,
    `src/config/mongoConnect.${ext}`,
    `src/config/__env.${ext}`,
  ];
}

/** Files generated by the Redis handler (only if useRedis is true). */
function redisFiles(language) {
  const ext = language === "ts" ? "ts" : "js";
  const files = [
    `src/redis/redis-client.${ext}`,
    `src/redis/redis.config.${ext}`,
    `src/redis/redis.errors.${ext}`,
    `src/redis/index.${ext}`,
    `src/redis/redis.bootstrap.${ext}`,
  ];
  if (language === "ts") {
    files.push("src/redis/redis.types.ts");
  }
  return files;
}

/** Files generated by the ESLint setup (only if useEslint is true). */
function eslintFiles() {
  return ["eslint.config.mjs"];
}

/** Files generated by the Vitest template (only if useVitest is true). */
function vitestFiles() {
  // Vitest only contributes a package.snippet.json (merged away), no extra files.
  return [];
}

/** All files expected for a given scenario. */
function expectedFilesFor(scenario) {
  const { language, orm, database, useRedis, useEslint, useVitest } = scenario;
  const files = new Set([...commonFiles(language)]);

  if (language === "ts") {
    for (const f of tsOnlyFiles()) files.add(f);
  }

  if (orm === "prisma") {
    for (const f of prismaFiles(language)) files.add(f);
  } else if (orm === "drizzle") {
    for (const f of drizzleFiles(language, database)) files.add(f);
  } else if (orm === "mongoose") {
    for (const f of mongooseFiles(language)) files.add(f);
  }

  if (useRedis) {
    for (const f of redisFiles(language)) files.add(f);
  }
  if (useEslint) {
    for (const f of eslintFiles()) files.add(f);
  }
  if (useVitest) {
    for (const f of vitestFiles()) files.add(f);
  }

  return [...files].sort();
}

// ===========================================================================
// package.json expectations
// ===========================================================================

/** Scripts from the base template (ts template has more scripts than js). */
const TEMPLATE_SCRIPTS = {
  ts: ["dev", "build", "start", "preview"],
  js: ["dev", "preview"],
};

/** Dependencies / devDependencies per ORM+database from template snippets. */
const ORM_DB_DEPS = {
  "prisma:postgresql": {
    dependencies: ["@prisma/client", "@prisma/adapter-pg", "pg"],
    devDependencies: ["prisma"],
  },
  "prisma:mysql": {
    dependencies: ["@prisma/client", "@prisma/adapter-mariadb", "mariadb"],
    devDependencies: ["prisma"],
  },
  "prisma:sqlite": {
    dependencies: ["@prisma/client", "@prisma/adapter-better-sqlite3", "better-sqlite3"],
    devDependencies: ["prisma", "@types/better-sqlite3"],
  },
  "drizzle:postgresql": {
    dependencies: ["drizzle-orm", "pg"],
    devDependencies: ["drizzle-kit", "@types/pg"],
  },
  "drizzle:mysql": {
    dependencies: ["drizzle-orm", "mysql2"],
    devDependencies: ["drizzle-kit"],
  },
  "drizzle:sqlite": {
    dependencies: ["drizzle-orm", "@libsql/client", "better-sqlite3"],
    devDependencies: ["drizzle-kit", "@types/better-sqlite3"],
  },
  "mongoose:mongodb": {
    dependencies: ["mongoose"],
    devDependencies: [],
  },
};

/** Additional per-orm scripts from snippets (not template). */
const ORM_SCRIPTS = {
  prisma: ["build-schema", "db:generate", "db:migrate"],
  drizzle: ["db:generate"],
  mongoose: [],
};

/** Extra drizzle db scripts per database. */
const DRIZZLE_DB_SCRIPTS = {
  postgresql: ["db:migrate"],
  mysql: ["db:push", "db:migrate", "db:migrate:prod", "db:reset", "db:studio", "db:check", "db:drop"],
  sqlite: ["db:migrate", "db:push", "db:studio", "db:seed"],
};

/** ESLint scripts (only when useEslint). */
const ESLINT_SCRIPTS = ["lint", "lint:fix"];

/** Vitest script (only when useVitest). */
const VITEST_SCRIPTS = ["test"];

const ESLINT_DEV_DEPS = ["eslint", "@eslint/js"];
const TS_ESLINT_DEV_DEPS = ["typescript-eslint"];

const TS_TEMPLATE_DEVS = ["typescript", "@types/node", "tsx", "ts-node", "ts-node-dev"];

function expectedScriptsFor(scenario) {
  const { language, orm, database, useEslint, useVitest } = scenario;
  const scripts = new Set([...TEMPLATE_SCRIPTS[language], ...ORM_SCRIPTS[orm]]);
  if (orm === "drizzle") {
    for (const s of DRIZZLE_DB_SCRIPTS[database]) scripts.add(s);
  }
  if (useEslint) {
    for (const s of ESLINT_SCRIPTS) scripts.add(s);
  }
  if (useVitest) {
    for (const s of VITEST_SCRIPTS) scripts.add(s);
  }
  return [...scripts].sort();
}

function expectedDepsFor(scenario) {
  const { orm, database, useRedis } = scenario;
  const deps = new Set(["subatom", ...ORM_DB_DEPS[`${orm}:${database}`].dependencies]);
  if (useRedis) deps.add("ioredis");
  return [...deps].sort();
}

function expectedDevDepsFor(scenario) {
  const { language, orm, database, useEslint } = scenario;
  const devDeps = new Set([...ORM_DB_DEPS[`${orm}:${database}`].devDependencies]);
  if (language === "ts") {
    for (const d of TS_TEMPLATE_DEVS) devDeps.add(d);
  }
  if (useEslint) {
    for (const d of ESLINT_DEV_DEPS) devDeps.add(d);
    if (language === "ts") {
      for (const d of TS_ESLINT_DEV_DEPS) devDeps.add(d);
    }
  }
  if (scenario.useVitest) devDeps.add("vitest");
  return [...devDeps].sort();
}

// ===========================================================================
// Helpers
// ===========================================================================

let passCount = 0;
let failCount = 0;

function log(step, message) {
  console.log(`\n[${step}] ${message}`);
}

function assert(condition, message) {
  if (!condition) {
    throw new Error(`ASSERTION FAILED: ${message}`);
  }
}

function buildCli() {
  if (existsSync(CLI_ENTRY)) {
    log("BUILD", "CLI already built, skipping build.");
    return;
  }
  log("BUILD", "Building create-subatom CLI...");
  const result = spawnSync("npm", ["run", "build"], {
    cwd: PROJECT_ROOT,
    stdio: "inherit",
    shell: true,
  });
  if (result.status !== 0) {
    throw new Error("Failed to build create-subatom CLI");
  }
  log("BUILD", "CLI built successfully.");
}

function scenarioLabel(scenario) {
  const features = [];
  if (scenario.useRedis) features.push("redis");
  if (scenario.useEslint) features.push("eslint");
  if (scenario.useVitest) features.push("vitest");
  return (
    `${scenario.language}/${scenario.orm}/${scenario.database}` +
    (features.length ? ` [+${features.join(",")}]` : " [no features]")
  );
}

function runExpectDriver(targetDir, scenario) {
  const label = scenarioLabel(scenario);
  log("RUN", `[${label}] Driving interactive CLI in ${targetDir}...`);
  const result = spawnSync(
    "expect",
    [
      EXPECT_DRIVER,
      scenario.projectName,
      targetDir,
      CLI_ENTRY,
      scenario.language,
      scenario.useRedis ? "yes" : "no",
      scenario.useEslint ? "yes" : "no",
      scenario.useVitest ? "yes" : "no",
      scenario.orm,
      scenario.database,
    ],
    { stdio: "inherit", shell: false },
  );
  if (result.status !== 0) {
    throw new Error(`Expect driver failed with exit code ${result.status}`);
  }
  log("RUN", `[${label}] CLI completed successfully.`);
}

function verifyProjectStructure(projectDir, scenario) {
  const label = scenarioLabel(scenario);
  log("VERIFY", `[${label}] Verifying generated project structure...`);
  const expectedFiles = expectedFilesFor(scenario);
  for (const relPath of expectedFiles) {
    const fullPath = path.join(projectDir, relPath);
    assert(
      existsSync(fullPath),
      `[${label}] Expected file "${relPath}" was not generated.`,
    );
  }
  log("VERIFY", `[${label}] All ${expectedFiles.length} expected files exist.`);
}

function verifyPackageJson(projectDir, scenario) {
  const label = scenarioLabel(scenario);
  log("VERIFY", `[${label}] Verifying package.json contents...`);
  const pkgPath = path.join(projectDir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

  assert(pkg.name === scenario.projectName, `[${label}] package.json name mismatch`);
  assert(pkg.private === true, `[${label}] package.json should be private`);

  // Scripts
  const expectedScripts = expectedScriptsFor(scenario);
  assert(
    pkg.scripts && typeof pkg.scripts === "object",
    `[${label}] package.json should have scripts`,
  );
  for (const script of expectedScripts) {
    assert(
      typeof pkg.scripts[script] === "string",
      `[${label}] package.json should have script "${script}"`,
    );
  }

  // Dependencies
  const expectedDeps = expectedDepsFor(scenario);
  assert(
    pkg.dependencies && typeof pkg.dependencies === "object",
    `[${label}] package.json should have dependencies`,
  );
  for (const dep of expectedDeps) {
    assert(
      typeof pkg.dependencies[dep] === "string",
      `[${label}] package.json should have dependency "${dep}"`,
    );
  }

  // DevDependencies
  const expectedDevDeps = expectedDevDepsFor(scenario);
  assert(
    pkg.devDependencies && typeof pkg.devDependencies === "object",
    `[${label}] package.json should have devDependencies`,
  );
  for (const dep of expectedDevDeps) {
    assert(
      typeof pkg.devDependencies[dep] === "string",
      `[${label}] package.json should have devDependency "${dep}"`,
    );
  }

  log("VERIFY", `[${label}] package.json contents verified.`);
}

function verifyFeatureToggles(projectDir, scenario) {
  const label = scenarioLabel(scenario);
  log("VERIFY", `[${label}] Verifying feature toggles (only enabled features present)...`);

  // If Redis is disabled, there must be no src/redis directory.
  if (!scenario.useRedis) {
    const redisDir = path.join(projectDir, "src", "redis");
    assert(!existsSync(redisDir), `[${label}] Redis files should NOT exist when Redis is disabled`);
  }
  // If ESLint is disabled, there must be no eslint.config.mjs.
  if (!scenario.useEslint) {
    const eslintConfig = path.join(projectDir, "eslint.config.mjs");
    assert(!existsSync(eslintConfig), `[${label}] eslint.config.mjs should NOT exist when ESLint is disabled`);
  }
  // If Vitest is disabled, there must be no "test" script from vitest.
  if (!scenario.useVitest) {
    const pkg = JSON.parse(readFileSync(path.join(projectDir, "package.json"), "utf8"));
    assert(
      pkg.scripts?.["test"] === undefined,
      `[${label}] "test" script should NOT exist when Vitest is disabled`,
    );
  }

  log("VERIFY", `[${label}] Feature toggles verified.`);
}

function verifyGitRepo(projectDir, scenario) {
  const label = scenarioLabel(scenario);
  log("VERIFY", `[${label}] Verifying git repository was initialized...`);
  const gitDir = path.join(projectDir, ".git");
  assert(existsSync(gitDir), `[${label}] Expected .git directory to exist`);

  const result = spawnSync("git", ["log", "--oneline"], {
    cwd: projectDir,
    encoding: "utf8",
  });
  assert(result.status === 0, `[${label}] git log should succeed`);
  assert(
    result.stdout.trim().length > 0,
    `[${label}] Expected at least one git commit`,
  );
  log("VERIFY", `[${label}] Git repository verified.`);
}

function verifyNoSnippetFiles(projectDir, scenario) {
  const label = scenarioLabel(scenario);
  log("VERIFY", `[${label}] Verifying no package.snippet files remain...`);
  const result = spawnSync(
    "find",
    [projectDir, "-name", "package.snippet*.json", "-not", "-path", "*/node_modules/*"],
    { encoding: "utf8" },
  );
  assert(
    result.stdout.trim() === "",
    `[${label}] Found leftover snippet files: ${result.stdout.trim()}`,
  );
  log("VERIFY", `[${label}] No leftover snippet files.`);
}

// ===========================================================================
// Main
// ===========================================================================

// Each scenario gets its own uniquely-named project directory.
let scenarioIndex = 0;

function main() {
  log("START", `Starting comprehensive create-subatom E2E test (${ALL_SCENARIOS.length} scenarios)...`);

  // 1. Build the CLI if needed
  buildCli();

  // 2. Create a single temp root for all scenarios
  const tempRoot = mkdtempSync(path.join(tmpdir(), "subatom-e2e-"));
  log("SETUP", `Temp working dir: ${tempRoot}`);

  try {
    // 3. Run every scenario
    for (const scenario of ALL_SCENARIOS) {
      scenarioIndex += 1;
      const label = scenarioLabel(scenario);
      const projectName = `e2e-${scenarioIndex}`;
      const projectDir = path.join(tempRoot, projectName);
      log("SCENARIO", `\n======================================================`);
      log("SCENARIO", `Scenario ${scenarioIndex}/${ALL_SCENARIOS.length}: ${label}`);
      log("SCENARIO", `Project: ${projectName}`);
      log("SCENARIO", `======================================================`);

      const enrichedScenario = { ...scenario, projectName };
      try {
        runExpectDriver(tempRoot, enrichedScenario);
        verifyProjectStructure(path.join(tempRoot, projectName), enrichedScenario);
        verifyPackageJson(path.join(tempRoot, projectName), enrichedScenario);
        verifyFeatureToggles(path.join(tempRoot, projectName), enrichedScenario);
        verifyGitRepo(path.join(tempRoot, projectName), enrichedScenario);
        verifyNoSnippetFiles(path.join(tempRoot, projectName), enrichedScenario);
        passCount += 1;
        console.log(`\n✅ Scenario PASSED: ${label}`);
      } catch (err) {
        failCount += 1;
        console.error(`\n❌ Scenario FAILED: ${label}`);
        console.error(err.message);
      }
    }
  } finally {
    // 5. Clean up
    log("CLEANUP", `Removing temp dir: ${tempRoot}`);
    rmSync(tempRoot, { recursive: true, force: true });
  }

  // 6. Summary
  log("SUMMARY", `Passed: ${passCount} | Failed: ${failCount} | Total: ${ALL_SCENARIOS.length}`);
  if (failCount > 0) {
    console.error(`\n❌ create-subatom E2E test FAILED (${failCount} scenario(s) failed)`);
    process.exit(1);
  }
  console.log(`\n✅ create-subatom E2E test PASSED (${passCount} scenarios)`);
}

main();